import { ethers } from "hardhat";
import { expect } from 'chai';
import MarketplaceManager from "../artifacts/contracts/marketplace/MarketplaceManager.sol/MarketplaceManager.json";
import addresses from "../addresses-folion.json";
import { IERC20__factory } from "../typechain-types"; // Generated by TypeChain
import { EventLog } from "ethers";

async function main() {
  const tokenAddress = "0x488Ef562D0a2fd97FdB716deE6F9875F041D9168"; // replace with actual token address
  const [_, user1, user2] = await ethers.getSigners();

  const marketplaceManager = await ethers.getContractAt(MarketplaceManager.abi, addresses.marketplaceManager);
  // Attach to the ERC20 contract
  const eth = IERC20__factory.connect(tokenAddress, user1);

  // log initial balances
  const balance1 = await eth.balanceOf(user1.address);
  console.log(`Initial Balance of ${user1.address}: ${ethers.formatEther(balance1)} ETH`);
  const balance2 = await eth.balanceOf(user2.address);
  console.log(`Initial Balance of ${user2.address}: ${ethers.formatEther(balance2)} ETH`);

  // Approve the marketplace manager to spend tokens on behalf of user1
  let approveTx = await eth.connect(user1).approve(ethers.getAddress(addresses.marketplaceManager), ethers.parseEther("10"));
  await approveTx.wait();
  console.log(`Approved ${marketplaceManager.address} to spend 10 ETH on behalf of ${user1.address}`);
  approveTx = await eth.connect(user2).approve(ethers.getAddress(addresses.marketplaceManager), ethers.parseEther("20"));
  await approveTx.wait();
  console.log(`Approved ${marketplaceManager.address} to spend 20 ETH on behalf of ${user2.address}`);

  // User1 initiates a transfer of 10 ETH to User2 in exchange for 20 ETH
  // the same applies to mint & burn, in that case investor is always user1,
  // for mint user1 sends USDC to receive newly minted tokens from user2 (the token contract)
  // for burn user1 sends tokens to burn and receive USDC from user2 
  const txInit = await marketplaceManager.connect(user1).initiateTransfer(
    tokenAddress,
    ethers.parseEther("10"),
    user2.address,
    tokenAddress,
    ethers.parseEther("20")
  );
  const receipt = await txInit.wait();
  console.log(`Initiated transfer of 10 ETH from ${user1.address} to ${user2.address}`);
  expect(txInit).to.emit(marketplaceManager, "TransferInitiated");
  const transferInitiatedEvent = receipt.logs.find((log: EventLog) => log.eventName === 'TransferInitiated')
  console.log('transferID:', transferInitiatedEvent.args[0]);

  // Now user2 takes the transfer
  const txTake = await marketplaceManager.connect(user2).takeTransfer(transferInitiatedEvent.args[0]);
  await txTake.wait();
  console.log(`Transfer completed`);
  expect(txTake).to.emit(marketplaceManager, "TransferExecuted");

  expect(await eth.balanceOf(user1.address)).to.equal(balance1 - ethers.parseEther("10") + ethers.parseEther("20"));
  expect(await eth.balanceOf(user2.address)).to.equal(balance2 + ethers.parseEther("10") - ethers.parseEther("20"));
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main().catch((error) => {
  console.error(error)
  process.exitCode = 1
});
