name: Solidity CI

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npx hardhat test --network hardhat
        env:
          REPORT_GAS: ${{ vars.REPORT_GAS }}
